version: "3"
services:
  postgres:
    image: docker-postgres-world-db-master:latest
    expose:
    - 5432
    ports:
      - 5432:5432
    environment:
         - POSTGRES_PASSWORD=world123
         - POSTGRES_USER=world
         - POSTGRES_DB=world-db
    restart: unless-stopped
# APP*****************************************
  springbootapp:
    image: gs-spring-boot-docker-complete:latest
    expose:
      - 8080
    ports:
      - 8080:8080
    restart: unless-stopped
    depends_on:
      - postgres
    links:
      - postgres
